### ISSUE TITLE
Remote Access OAuth Error

### ISSUE THREAD

**Issue by ddv131** [thedges/PSEADashboardFilterGenerator#1]
Hi there,

I'm having the OAuth error and followed your steps to resolve this by adding a remote site but it still isn't working.  I tried adding the sandbox url https://cs107.salesforce.com as a remote site but this hasn't made any difference.

I'm able to deploy to production (but I stop before actually installing) as I need to test in the sandbox before I can put anything into prod.

I can't see why it will authorise prod but not the sandbox when this was only created in the last few days and there hasn't been any other changes to my user, permissions or system settings.

Any ideas please?

Thanks.

**Comment by thedges** [comment]
Can you send me a screenshot of the exact error you are getting? I will try to help but to be honest, this is a demo component I built to use internal to my company and I haven't tested this on sandboxes (I actually don't have access to sandbox...only trial and dev orgs).

**Comment by ddv131** [comment]
![oauth error](https://user-images.githubusercontent.com/44437207/47446019-2e8dde00-d7b2-11e8-8e86-f07684895507.JPG)

Hi Troy, please find attached the screenshot.

One of the Solution Engineers at Salesforce pointed me to this as he himself had struggled with the filters until finding your tool.

Many thanks.

**Comment by thedges** [comment]
Thanks. When exactly is this error showing up (i.e. what did you click on right before this error showed)?

**Comment by ddv131** [comment]
![deploy](https://user-images.githubusercontent.com/44437207/47484225-19a55f00-d833-11e8-84c5-e81e624e4ab2.JPG)

1. I click the Deploy to Salesforce button at the bottom
2. The deploy to Salesforce page then shows up (see above)
3. I select the Sandbox option and click Login to Salesforce
4. I then get the usual choose a username screen
5. I input my sandbox credentials and click Log in to Sandbox and then the error appears

**Comment by thedges** [comment]
Awww...I see now. I thought you were having an issue with actual component and the error was throwing me off as it shouldn't use OAuth. Problem is I don't have a sandbox instance to test against. Try this....1) clear your browser cache, 2) login to your sandbox as yourself, 3) then in same browser sessions...go to the component github repo and try to deploy to your sandbox again. Let me know if that changes anything.

**Comment by ddv131** [comment]
Hi Troy, I tried what you suggested and that didn't resolve the issue unfortunately.

What's a bit weird is that I have a really old dev org on na47.salesforce.com which allowed me to deploy the tool fine, but when I tried to deploy to another dev org (eu13) it failed with the OAuth error.

Could the server location be playing a part?

I've tried checking various setup settings between the two orgs and nothing jumps out as being different which I can see.

**Comment by ddv131** [comment]
Hi Troy, just wondered if you had any advice before I give up?  I think I'm going to be a bit stuck even if we manage to install the tool as we don't have My Domain enabled which seems to be a requirement unfortunately.

Appreciate all your support so far.

**Comment by thedges** [comment]
First, you will need MyDomain enabled for lightning components.

I use a 3rd party deploy tool (see here: https://github.com/afawcett/githubsfdeploy) that does the actual deployment to orgs. Suggest to reach out to Andy and see if he has any recommendations.

As last resort, I created an unmanaged package (see install url below) that you could try. Guessing it will fail as I don't have any test code coverage in my code. So might need to add that at some point.

https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000003xpsP
